// Code generated by ent, DO NOT EDIT.

package tag

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/interngowhere/web-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Tag {
	return predicate.Tag(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Tag {
	return predicate.Tag(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Tag {
	return predicate.Tag(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Tag {
	return predicate.Tag(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Tag {
	return predicate.Tag(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Tag {
	return predicate.Tag(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Tag {
	return predicate.Tag(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Tag {
	return predicate.Tag(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Tag {
	return predicate.Tag(sql.FieldLTE(FieldID, id))
}

// TagName applies equality check predicate on the "tag_name" field. It's identical to TagNameEQ.
func TagName(v string) predicate.Tag {
	return predicate.Tag(sql.FieldEQ(FieldTagName, v))
}

// TagDescription applies equality check predicate on the "tag_description" field. It's identical to TagDescriptionEQ.
func TagDescription(v string) predicate.Tag {
	return predicate.Tag(sql.FieldEQ(FieldTagDescription, v))
}

// TagNameEQ applies the EQ predicate on the "tag_name" field.
func TagNameEQ(v string) predicate.Tag {
	return predicate.Tag(sql.FieldEQ(FieldTagName, v))
}

// TagNameNEQ applies the NEQ predicate on the "tag_name" field.
func TagNameNEQ(v string) predicate.Tag {
	return predicate.Tag(sql.FieldNEQ(FieldTagName, v))
}

// TagNameIn applies the In predicate on the "tag_name" field.
func TagNameIn(vs ...string) predicate.Tag {
	return predicate.Tag(sql.FieldIn(FieldTagName, vs...))
}

// TagNameNotIn applies the NotIn predicate on the "tag_name" field.
func TagNameNotIn(vs ...string) predicate.Tag {
	return predicate.Tag(sql.FieldNotIn(FieldTagName, vs...))
}

// TagNameGT applies the GT predicate on the "tag_name" field.
func TagNameGT(v string) predicate.Tag {
	return predicate.Tag(sql.FieldGT(FieldTagName, v))
}

// TagNameGTE applies the GTE predicate on the "tag_name" field.
func TagNameGTE(v string) predicate.Tag {
	return predicate.Tag(sql.FieldGTE(FieldTagName, v))
}

// TagNameLT applies the LT predicate on the "tag_name" field.
func TagNameLT(v string) predicate.Tag {
	return predicate.Tag(sql.FieldLT(FieldTagName, v))
}

// TagNameLTE applies the LTE predicate on the "tag_name" field.
func TagNameLTE(v string) predicate.Tag {
	return predicate.Tag(sql.FieldLTE(FieldTagName, v))
}

// TagNameContains applies the Contains predicate on the "tag_name" field.
func TagNameContains(v string) predicate.Tag {
	return predicate.Tag(sql.FieldContains(FieldTagName, v))
}

// TagNameHasPrefix applies the HasPrefix predicate on the "tag_name" field.
func TagNameHasPrefix(v string) predicate.Tag {
	return predicate.Tag(sql.FieldHasPrefix(FieldTagName, v))
}

// TagNameHasSuffix applies the HasSuffix predicate on the "tag_name" field.
func TagNameHasSuffix(v string) predicate.Tag {
	return predicate.Tag(sql.FieldHasSuffix(FieldTagName, v))
}

// TagNameEqualFold applies the EqualFold predicate on the "tag_name" field.
func TagNameEqualFold(v string) predicate.Tag {
	return predicate.Tag(sql.FieldEqualFold(FieldTagName, v))
}

// TagNameContainsFold applies the ContainsFold predicate on the "tag_name" field.
func TagNameContainsFold(v string) predicate.Tag {
	return predicate.Tag(sql.FieldContainsFold(FieldTagName, v))
}

// TagDescriptionEQ applies the EQ predicate on the "tag_description" field.
func TagDescriptionEQ(v string) predicate.Tag {
	return predicate.Tag(sql.FieldEQ(FieldTagDescription, v))
}

// TagDescriptionNEQ applies the NEQ predicate on the "tag_description" field.
func TagDescriptionNEQ(v string) predicate.Tag {
	return predicate.Tag(sql.FieldNEQ(FieldTagDescription, v))
}

// TagDescriptionIn applies the In predicate on the "tag_description" field.
func TagDescriptionIn(vs ...string) predicate.Tag {
	return predicate.Tag(sql.FieldIn(FieldTagDescription, vs...))
}

// TagDescriptionNotIn applies the NotIn predicate on the "tag_description" field.
func TagDescriptionNotIn(vs ...string) predicate.Tag {
	return predicate.Tag(sql.FieldNotIn(FieldTagDescription, vs...))
}

// TagDescriptionGT applies the GT predicate on the "tag_description" field.
func TagDescriptionGT(v string) predicate.Tag {
	return predicate.Tag(sql.FieldGT(FieldTagDescription, v))
}

// TagDescriptionGTE applies the GTE predicate on the "tag_description" field.
func TagDescriptionGTE(v string) predicate.Tag {
	return predicate.Tag(sql.FieldGTE(FieldTagDescription, v))
}

// TagDescriptionLT applies the LT predicate on the "tag_description" field.
func TagDescriptionLT(v string) predicate.Tag {
	return predicate.Tag(sql.FieldLT(FieldTagDescription, v))
}

// TagDescriptionLTE applies the LTE predicate on the "tag_description" field.
func TagDescriptionLTE(v string) predicate.Tag {
	return predicate.Tag(sql.FieldLTE(FieldTagDescription, v))
}

// TagDescriptionContains applies the Contains predicate on the "tag_description" field.
func TagDescriptionContains(v string) predicate.Tag {
	return predicate.Tag(sql.FieldContains(FieldTagDescription, v))
}

// TagDescriptionHasPrefix applies the HasPrefix predicate on the "tag_description" field.
func TagDescriptionHasPrefix(v string) predicate.Tag {
	return predicate.Tag(sql.FieldHasPrefix(FieldTagDescription, v))
}

// TagDescriptionHasSuffix applies the HasSuffix predicate on the "tag_description" field.
func TagDescriptionHasSuffix(v string) predicate.Tag {
	return predicate.Tag(sql.FieldHasSuffix(FieldTagDescription, v))
}

// TagDescriptionEqualFold applies the EqualFold predicate on the "tag_description" field.
func TagDescriptionEqualFold(v string) predicate.Tag {
	return predicate.Tag(sql.FieldEqualFold(FieldTagDescription, v))
}

// TagDescriptionContainsFold applies the ContainsFold predicate on the "tag_description" field.
func TagDescriptionContainsFold(v string) predicate.Tag {
	return predicate.Tag(sql.FieldContainsFold(FieldTagDescription, v))
}

// HasTaggedThreads applies the HasEdge predicate on the "tagged_threads" edge.
func HasTaggedThreads() predicate.Tag {
	return predicate.Tag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, TaggedThreadsTable, TaggedThreadsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaggedThreadsWith applies the HasEdge predicate on the "tagged_threads" edge with a given conditions (other predicates).
func HasTaggedThreadsWith(preds ...predicate.Thread) predicate.Tag {
	return predicate.Tag(func(s *sql.Selector) {
		step := newTaggedThreadsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Tag) predicate.Tag {
	return predicate.Tag(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Tag) predicate.Tag {
	return predicate.Tag(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tag) predicate.Tag {
	return predicate.Tag(sql.NotPredicates(p))
}
