// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/interngowhere/web-backend/ent/comment"
	"github.com/interngowhere/web-backend/ent/commentkudo"
	"github.com/interngowhere/web-backend/ent/user"
)

// CommentKudoCreate is the builder for creating a CommentKudo entity.
type CommentKudoCreate struct {
	config
	mutation *CommentKudoMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (ckc *CommentKudoCreate) SetUserID(u uuid.UUID) *CommentKudoCreate {
	ckc.mutation.SetUserID(u)
	return ckc
}

// SetCommentID sets the "comment_id" field.
func (ckc *CommentKudoCreate) SetCommentID(i int) *CommentKudoCreate {
	ckc.mutation.SetCommentID(i)
	return ckc
}

// SetUser sets the "user" edge to the User entity.
func (ckc *CommentKudoCreate) SetUser(u *User) *CommentKudoCreate {
	return ckc.SetUserID(u.ID)
}

// SetComment sets the "comment" edge to the Comment entity.
func (ckc *CommentKudoCreate) SetComment(c *Comment) *CommentKudoCreate {
	return ckc.SetCommentID(c.ID)
}

// Mutation returns the CommentKudoMutation object of the builder.
func (ckc *CommentKudoCreate) Mutation() *CommentKudoMutation {
	return ckc.mutation
}

// Save creates the CommentKudo in the database.
func (ckc *CommentKudoCreate) Save(ctx context.Context) (*CommentKudo, error) {
	return withHooks(ctx, ckc.sqlSave, ckc.mutation, ckc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ckc *CommentKudoCreate) SaveX(ctx context.Context) *CommentKudo {
	v, err := ckc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ckc *CommentKudoCreate) Exec(ctx context.Context) error {
	_, err := ckc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ckc *CommentKudoCreate) ExecX(ctx context.Context) {
	if err := ckc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ckc *CommentKudoCreate) check() error {
	if _, ok := ckc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CommentKudo.user_id"`)}
	}
	if _, ok := ckc.mutation.CommentID(); !ok {
		return &ValidationError{Name: "comment_id", err: errors.New(`ent: missing required field "CommentKudo.comment_id"`)}
	}
	if _, ok := ckc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CommentKudo.user"`)}
	}
	if _, ok := ckc.mutation.CommentID(); !ok {
		return &ValidationError{Name: "comment", err: errors.New(`ent: missing required edge "CommentKudo.comment"`)}
	}
	return nil
}

func (ckc *CommentKudoCreate) sqlSave(ctx context.Context) (*CommentKudo, error) {
	if err := ckc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ckc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ckc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ckc.mutation.id = &_node.ID
	ckc.mutation.done = true
	return _node, nil
}

func (ckc *CommentKudoCreate) createSpec() (*CommentKudo, *sqlgraph.CreateSpec) {
	var (
		_node = &CommentKudo{config: ckc.config}
		_spec = sqlgraph.NewCreateSpec(commentkudo.Table, sqlgraph.NewFieldSpec(commentkudo.FieldID, field.TypeInt))
	)
	if nodes := ckc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commentkudo.UserTable,
			Columns: []string{commentkudo.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ckc.mutation.CommentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   commentkudo.CommentTable,
			Columns: []string{commentkudo.CommentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CommentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CommentKudoCreateBulk is the builder for creating many CommentKudo entities in bulk.
type CommentKudoCreateBulk struct {
	config
	err      error
	builders []*CommentKudoCreate
}

// Save creates the CommentKudo entities in the database.
func (ckcb *CommentKudoCreateBulk) Save(ctx context.Context) ([]*CommentKudo, error) {
	if ckcb.err != nil {
		return nil, ckcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ckcb.builders))
	nodes := make([]*CommentKudo, len(ckcb.builders))
	mutators := make([]Mutator, len(ckcb.builders))
	for i := range ckcb.builders {
		func(i int, root context.Context) {
			builder := ckcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommentKudoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ckcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ckcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ckcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ckcb *CommentKudoCreateBulk) SaveX(ctx context.Context) []*CommentKudo {
	v, err := ckcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ckcb *CommentKudoCreateBulk) Exec(ctx context.Context) error {
	_, err := ckcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ckcb *CommentKudoCreateBulk) ExecX(ctx context.Context) {
	if err := ckcb.Exec(ctx); err != nil {
		panic(err)
	}
}
