// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/interngowhere/web-backend/ent/comment"
	"github.com/interngowhere/web-backend/ent/commentkudo"
	"github.com/interngowhere/web-backend/ent/user"
)

// CommentKudo is the model entity for the CommentKudo schema.
type CommentKudo struct {
	config `json:"-"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// CommentID holds the value of the "comment_id" field.
	CommentID int `json:"comment_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CommentKudoQuery when eager-loading is set.
	Edges        CommentKudoEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CommentKudoEdges holds the relations/edges for other nodes in the graph.
type CommentKudoEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Comment holds the value of the comment edge.
	Comment *Comment `json:"comment,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommentKudoEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// CommentOrErr returns the Comment value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommentKudoEdges) CommentOrErr() (*Comment, error) {
	if e.loadedTypes[1] {
		if e.Comment == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: comment.Label}
		}
		return e.Comment, nil
	}
	return nil, &NotLoadedError{edge: "comment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CommentKudo) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case commentkudo.FieldCommentID:
			values[i] = new(sql.NullInt64)
		case commentkudo.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CommentKudo fields.
func (ck *CommentKudo) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case commentkudo.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				ck.UserID = *value
			}
		case commentkudo.FieldCommentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field comment_id", values[i])
			} else if value.Valid {
				ck.CommentID = int(value.Int64)
			}
		default:
			ck.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CommentKudo.
// This includes values selected through modifiers, order, etc.
func (ck *CommentKudo) Value(name string) (ent.Value, error) {
	return ck.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CommentKudo entity.
func (ck *CommentKudo) QueryUser() *UserQuery {
	return NewCommentKudoClient(ck.config).QueryUser(ck)
}

// QueryComment queries the "comment" edge of the CommentKudo entity.
func (ck *CommentKudo) QueryComment() *CommentQuery {
	return NewCommentKudoClient(ck.config).QueryComment(ck)
}

// Update returns a builder for updating this CommentKudo.
// Note that you need to call CommentKudo.Unwrap() before calling this method if this CommentKudo
// was returned from a transaction, and the transaction was committed or rolled back.
func (ck *CommentKudo) Update() *CommentKudoUpdateOne {
	return NewCommentKudoClient(ck.config).UpdateOne(ck)
}

// Unwrap unwraps the CommentKudo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ck *CommentKudo) Unwrap() *CommentKudo {
	_tx, ok := ck.config.driver.(*txDriver)
	if !ok {
		panic("ent: CommentKudo is not a transactional entity")
	}
	ck.config.driver = _tx.drv
	return ck
}

// String implements the fmt.Stringer.
func (ck *CommentKudo) String() string {
	var builder strings.Builder
	builder.WriteString("CommentKudo(")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ck.UserID))
	builder.WriteString(", ")
	builder.WriteString("comment_id=")
	builder.WriteString(fmt.Sprintf("%v", ck.CommentID))
	builder.WriteByte(')')
	return builder.String()
}

// CommentKudos is a parsable slice of CommentKudo.
type CommentKudos []*CommentKudo
