// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/interngowhere/web-backend/ent/moderator"
	"github.com/interngowhere/web-backend/ent/predicate"
	"github.com/interngowhere/web-backend/ent/topic"
	"github.com/interngowhere/web-backend/ent/user"
)

// ModeratorQuery is the builder for querying Moderator entities.
type ModeratorQuery struct {
	config
	ctx           *QueryContext
	order         []moderator.OrderOption
	inters        []Interceptor
	predicates    []predicate.Moderator
	withModerator *UserQuery
	withTopic     *TopicQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ModeratorQuery builder.
func (mq *ModeratorQuery) Where(ps ...predicate.Moderator) *ModeratorQuery {
	mq.predicates = append(mq.predicates, ps...)
	return mq
}

// Limit the number of records to be returned by this query.
func (mq *ModeratorQuery) Limit(limit int) *ModeratorQuery {
	mq.ctx.Limit = &limit
	return mq
}

// Offset to start from.
func (mq *ModeratorQuery) Offset(offset int) *ModeratorQuery {
	mq.ctx.Offset = &offset
	return mq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mq *ModeratorQuery) Unique(unique bool) *ModeratorQuery {
	mq.ctx.Unique = &unique
	return mq
}

// Order specifies how the records should be ordered.
func (mq *ModeratorQuery) Order(o ...moderator.OrderOption) *ModeratorQuery {
	mq.order = append(mq.order, o...)
	return mq
}

// QueryModerator chains the current query on the "moderator" edge.
func (mq *ModeratorQuery) QueryModerator() *UserQuery {
	query := (&UserClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(moderator.Table, moderator.ModeratorColumn, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, moderator.ModeratorTable, moderator.ModeratorColumn),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTopic chains the current query on the "topic" edge.
func (mq *ModeratorQuery) QueryTopic() *TopicQuery {
	query := (&TopicClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(moderator.Table, moderator.TopicColumn, selector),
			sqlgraph.To(topic.Table, topic.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, moderator.TopicTable, moderator.TopicColumn),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Moderator entity from the query.
// Returns a *NotFoundError when no Moderator was found.
func (mq *ModeratorQuery) First(ctx context.Context) (*Moderator, error) {
	nodes, err := mq.Limit(1).All(setContextOp(ctx, mq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{moderator.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mq *ModeratorQuery) FirstX(ctx context.Context) *Moderator {
	node, err := mq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single Moderator entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Moderator entity is found.
// Returns a *NotFoundError when no Moderator entities are found.
func (mq *ModeratorQuery) Only(ctx context.Context) (*Moderator, error) {
	nodes, err := mq.Limit(2).All(setContextOp(ctx, mq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{moderator.Label}
	default:
		return nil, &NotSingularError{moderator.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mq *ModeratorQuery) OnlyX(ctx context.Context) *Moderator {
	node, err := mq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of Moderators.
func (mq *ModeratorQuery) All(ctx context.Context) ([]*Moderator, error) {
	ctx = setContextOp(ctx, mq.ctx, "All")
	if err := mq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Moderator, *ModeratorQuery]()
	return withInterceptors[[]*Moderator](ctx, mq, qr, mq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mq *ModeratorQuery) AllX(ctx context.Context) []*Moderator {
	nodes, err := mq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (mq *ModeratorQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mq.ctx, "Count")
	if err := mq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mq, querierCount[*ModeratorQuery](), mq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mq *ModeratorQuery) CountX(ctx context.Context) int {
	count, err := mq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mq *ModeratorQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mq.ctx, "Exist")
	switch _, err := mq.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mq *ModeratorQuery) ExistX(ctx context.Context) bool {
	exist, err := mq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ModeratorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mq *ModeratorQuery) Clone() *ModeratorQuery {
	if mq == nil {
		return nil
	}
	return &ModeratorQuery{
		config:        mq.config,
		ctx:           mq.ctx.Clone(),
		order:         append([]moderator.OrderOption{}, mq.order...),
		inters:        append([]Interceptor{}, mq.inters...),
		predicates:    append([]predicate.Moderator{}, mq.predicates...),
		withModerator: mq.withModerator.Clone(),
		withTopic:     mq.withTopic.Clone(),
		// clone intermediate query.
		sql:  mq.sql.Clone(),
		path: mq.path,
	}
}

// WithModerator tells the query-builder to eager-load the nodes that are connected to
// the "moderator" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *ModeratorQuery) WithModerator(opts ...func(*UserQuery)) *ModeratorQuery {
	query := (&UserClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withModerator = query
	return mq
}

// WithTopic tells the query-builder to eager-load the nodes that are connected to
// the "topic" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *ModeratorQuery) WithTopic(opts ...func(*TopicQuery)) *ModeratorQuery {
	query := (&TopicClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withTopic = query
	return mq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ModeratorID uuid.UUID `json:"moderator_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Moderator.Query().
//		GroupBy(moderator.FieldModeratorID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mq *ModeratorQuery) GroupBy(field string, fields ...string) *ModeratorGroupBy {
	mq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ModeratorGroupBy{build: mq}
	grbuild.flds = &mq.ctx.Fields
	grbuild.label = moderator.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ModeratorID uuid.UUID `json:"moderator_id,omitempty"`
//	}
//
//	client.Moderator.Query().
//		Select(moderator.FieldModeratorID).
//		Scan(ctx, &v)
func (mq *ModeratorQuery) Select(fields ...string) *ModeratorSelect {
	mq.ctx.Fields = append(mq.ctx.Fields, fields...)
	sbuild := &ModeratorSelect{ModeratorQuery: mq}
	sbuild.label = moderator.Label
	sbuild.flds, sbuild.scan = &mq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ModeratorSelect configured with the given aggregations.
func (mq *ModeratorQuery) Aggregate(fns ...AggregateFunc) *ModeratorSelect {
	return mq.Select().Aggregate(fns...)
}

func (mq *ModeratorQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mq); err != nil {
				return err
			}
		}
	}
	for _, f := range mq.ctx.Fields {
		if !moderator.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mq.path != nil {
		prev, err := mq.path(ctx)
		if err != nil {
			return err
		}
		mq.sql = prev
	}
	return nil
}

func (mq *ModeratorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Moderator, error) {
	var (
		nodes       = []*Moderator{}
		_spec       = mq.querySpec()
		loadedTypes = [2]bool{
			mq.withModerator != nil,
			mq.withTopic != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Moderator).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Moderator{config: mq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mq.withModerator; query != nil {
		if err := mq.loadModerator(ctx, query, nodes, nil,
			func(n *Moderator, e *User) { n.Edges.Moderator = e }); err != nil {
			return nil, err
		}
	}
	if query := mq.withTopic; query != nil {
		if err := mq.loadTopic(ctx, query, nodes, nil,
			func(n *Moderator, e *Topic) { n.Edges.Topic = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mq *ModeratorQuery) loadModerator(ctx context.Context, query *UserQuery, nodes []*Moderator, init func(*Moderator), assign func(*Moderator, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Moderator)
	for i := range nodes {
		fk := nodes[i].ModeratorID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "moderator_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mq *ModeratorQuery) loadTopic(ctx context.Context, query *TopicQuery, nodes []*Moderator, init func(*Moderator), assign func(*Moderator, *Topic)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Moderator)
	for i := range nodes {
		fk := nodes[i].TopicID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(topic.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "topic_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mq *ModeratorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mq.querySpec()
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, mq.driver, _spec)
}

func (mq *ModeratorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(moderator.Table, moderator.Columns, nil)
	_spec.From = mq.sql
	if unique := mq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mq.path != nil {
		_spec.Unique = true
	}
	if fields := mq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if mq.withModerator != nil {
			_spec.Node.AddColumnOnce(moderator.FieldModeratorID)
		}
		if mq.withTopic != nil {
			_spec.Node.AddColumnOnce(moderator.FieldTopicID)
		}
	}
	if ps := mq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mq *ModeratorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mq.driver.Dialect())
	t1 := builder.Table(moderator.Table)
	columns := mq.ctx.Fields
	if len(columns) == 0 {
		columns = moderator.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mq.sql != nil {
		selector = mq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mq.ctx.Unique != nil && *mq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mq.predicates {
		p(selector)
	}
	for _, p := range mq.order {
		p(selector)
	}
	if offset := mq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ModeratorGroupBy is the group-by builder for Moderator entities.
type ModeratorGroupBy struct {
	selector
	build *ModeratorQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mgb *ModeratorGroupBy) Aggregate(fns ...AggregateFunc) *ModeratorGroupBy {
	mgb.fns = append(mgb.fns, fns...)
	return mgb
}

// Scan applies the selector query and scans the result into the given value.
func (mgb *ModeratorGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mgb.build.ctx, "GroupBy")
	if err := mgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModeratorQuery, *ModeratorGroupBy](ctx, mgb.build, mgb, mgb.build.inters, v)
}

func (mgb *ModeratorGroupBy) sqlScan(ctx context.Context, root *ModeratorQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mgb.fns))
	for _, fn := range mgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mgb.flds)+len(mgb.fns))
		for _, f := range *mgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ModeratorSelect is the builder for selecting fields of Moderator entities.
type ModeratorSelect struct {
	*ModeratorQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ms *ModeratorSelect) Aggregate(fns ...AggregateFunc) *ModeratorSelect {
	ms.fns = append(ms.fns, fns...)
	return ms
}

// Scan applies the selector query and scans the result into the given value.
func (ms *ModeratorSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ms.ctx, "Select")
	if err := ms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModeratorQuery, *ModeratorSelect](ctx, ms.ModeratorQuery, ms, ms.inters, v)
}

func (ms *ModeratorSelect) sqlScan(ctx context.Context, root *ModeratorQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ms.fns))
	for _, fn := range ms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
