// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/interngowhere/web-backend/ent/thread"
	"github.com/interngowhere/web-backend/ent/threadkudo"
	"github.com/interngowhere/web-backend/ent/user"
)

// ThreadKudoCreate is the builder for creating a ThreadKudo entity.
type ThreadKudoCreate struct {
	config
	mutation *ThreadKudoMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (tkc *ThreadKudoCreate) SetUserID(u uuid.UUID) *ThreadKudoCreate {
	tkc.mutation.SetUserID(u)
	return tkc
}

// SetThreadID sets the "thread_id" field.
func (tkc *ThreadKudoCreate) SetThreadID(i int) *ThreadKudoCreate {
	tkc.mutation.SetThreadID(i)
	return tkc
}

// SetUser sets the "user" edge to the User entity.
func (tkc *ThreadKudoCreate) SetUser(u *User) *ThreadKudoCreate {
	return tkc.SetUserID(u.ID)
}

// SetThread sets the "thread" edge to the Thread entity.
func (tkc *ThreadKudoCreate) SetThread(t *Thread) *ThreadKudoCreate {
	return tkc.SetThreadID(t.ID)
}

// Mutation returns the ThreadKudoMutation object of the builder.
func (tkc *ThreadKudoCreate) Mutation() *ThreadKudoMutation {
	return tkc.mutation
}

// Save creates the ThreadKudo in the database.
func (tkc *ThreadKudoCreate) Save(ctx context.Context) (*ThreadKudo, error) {
	return withHooks(ctx, tkc.sqlSave, tkc.mutation, tkc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tkc *ThreadKudoCreate) SaveX(ctx context.Context) *ThreadKudo {
	v, err := tkc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tkc *ThreadKudoCreate) Exec(ctx context.Context) error {
	_, err := tkc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tkc *ThreadKudoCreate) ExecX(ctx context.Context) {
	if err := tkc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tkc *ThreadKudoCreate) check() error {
	if _, ok := tkc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ThreadKudo.user_id"`)}
	}
	if _, ok := tkc.mutation.ThreadID(); !ok {
		return &ValidationError{Name: "thread_id", err: errors.New(`ent: missing required field "ThreadKudo.thread_id"`)}
	}
	if _, ok := tkc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ThreadKudo.user"`)}
	}
	if _, ok := tkc.mutation.ThreadID(); !ok {
		return &ValidationError{Name: "thread", err: errors.New(`ent: missing required edge "ThreadKudo.thread"`)}
	}
	return nil
}

func (tkc *ThreadKudoCreate) sqlSave(ctx context.Context) (*ThreadKudo, error) {
	if err := tkc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tkc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tkc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tkc.mutation.id = &_node.ID
	tkc.mutation.done = true
	return _node, nil
}

func (tkc *ThreadKudoCreate) createSpec() (*ThreadKudo, *sqlgraph.CreateSpec) {
	var (
		_node = &ThreadKudo{config: tkc.config}
		_spec = sqlgraph.NewCreateSpec(threadkudo.Table, sqlgraph.NewFieldSpec(threadkudo.FieldID, field.TypeInt))
	)
	if nodes := tkc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   threadkudo.UserTable,
			Columns: []string{threadkudo.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tkc.mutation.ThreadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   threadkudo.ThreadTable,
			Columns: []string{threadkudo.ThreadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ThreadID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ThreadKudoCreateBulk is the builder for creating many ThreadKudo entities in bulk.
type ThreadKudoCreateBulk struct {
	config
	err      error
	builders []*ThreadKudoCreate
}

// Save creates the ThreadKudo entities in the database.
func (tkcb *ThreadKudoCreateBulk) Save(ctx context.Context) ([]*ThreadKudo, error) {
	if tkcb.err != nil {
		return nil, tkcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tkcb.builders))
	nodes := make([]*ThreadKudo, len(tkcb.builders))
	mutators := make([]Mutator, len(tkcb.builders))
	for i := range tkcb.builders {
		func(i int, root context.Context) {
			builder := tkcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ThreadKudoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tkcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tkcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tkcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tkcb *ThreadKudoCreateBulk) SaveX(ctx context.Context) []*ThreadKudo {
	v, err := tkcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tkcb *ThreadKudoCreateBulk) Exec(ctx context.Context) error {
	_, err := tkcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tkcb *ThreadKudoCreateBulk) ExecX(ctx context.Context) {
	if err := tkcb.Exec(ctx); err != nil {
		panic(err)
	}
}
